//PROJECTS
export const SHOW_FORM_PROJECT = "SHOW_FORM_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const SELECT_PROJECT = "SELECT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

//TASKS
export const GET_TASKS = "GET_TASKS";
export const CREATE_TASK = "CREATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const EDIT_TASK = "EDIT_TASK";
// export const CHANGE_STATUS_TASK = "CHANGE_STATUS_TASK";
export const CHANGE_FORM_TO_EDIT_TASK = "CHANGE_FORM_TO_EDIT_TASK";
export const SELECT_TASK = "SELECT_TASK";
export const CLEAR_TASKS = "CLEAR_TASKS";


//ALERTS
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

//AUTH
export const SUCCESSFULL_REGISTRATION = "SUCCESSFULL_REGISTRATION";
export const FAILED_REGISTRATION = "FAILED_REGISTRATION";
export const GET_USER = "GET_USER";
export const SUCCESSFULL_LOGIN = "SUCCESSFULL_LOGIN";
export const FAILED_LOGIN = "FAILED_LOGIN";
export const CLOSE_SESION = "CLOSE_SESION";

